[package]
name = "eigen_crypto"
version = "0.1.0"
authors = ["stephen@ieigen.com"]
edition = "2018"

[features]
#---- begin for sgx
default = ["mesalock_sgx", "alloc"]
mesalock_sgx = ["sgx_tstd"]
#---- end
#default = ["alloc"]
#mesalock_sgx = []
alloc = []

[dependencies]
#---- begin for sgx
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["untrusted_fs"] }
sgx_libc = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

ring = { git = "https://github.com/mesalock-linux/ring-sgx", branch="v1.1.2-backup"}
rand = { path = "./vendor/rand-sgx" }
num-bigint = { path = "./vendor/num-bigint-sgx" }
rust-base58 =  {  path = "./vendor/rust-base58-sgx" }
rust-crypto = { path = "./vendor/rust-crypto-sgx" }
serde_json =  {  path = "./vendor/serde-json-sgx" }
serde_derive = { git = "https://github.com/mesalock-linux/serde-sgx", branch="v1.1.2-backup" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx", features = ["derive"], branch="v1.1.2-backup"}
#rand_chacha
lazy_static = { version = "1.2", features = ["spin_no_std"] }
num-traits = { git = "https://github.com/mesalock-linux/num-traits-sgx", branch="v1.1.2-backup" }
num-integer = {  path = "./vendor/num-integer-sgx" }
untrusted = { git = "https://github.com/briansmith/untrusted", tag = "ring-master" }
bytes = { git = "https://github.com/mesalock-linux/bytes-sgx", branch="v1.1.2-backup" }
regex = {  path = "./vendor/regex-sgx" }
#---- end

#ring         = "0.16.9"
#rand         = "0.7.2"
#num-bigint   =  { version = "0.2.3", features = ["serde"] }
#rust-base58 = "*"
#rust-crypto  = "0.2.36"
#serde        = {  version = "1.0.104", features = ["derive"]}
#serde_derive = "1.0.104"
#serde_json   = "1.0.40"
#rand_chacha  = "0.2.1"
#lazy_static  = "1.4.0"
#num-traits   = "0.2.10"
#num-integer  = "0.1.41"
#untrusted    = "0.7.0"
#libc         = "0.2.69"
#bytes        = { version = "0.4.12"} # unix app depends on 0.4.12, while sgx lib depends on 0.5.0
#regex        = "1"

[dev-dependencies]
hex = "0.4.0"
base64 = "0.12.1"
